### ISSUE TITLE
Nether RTP bug

### ISSUE THREAD

**Issue by HexedHero** [SuperRonanCraft/BetterRTP#10]
**Plugin Version**:

Version #2.8.3

**Describe The Bug**:

U can rtp ontop of the nether roof

**How To Reproduce**:

Rtp in Nether

**Expected Behavior**:

Not teleport ontop of the nether's roof

**Comment by SuperRonanCraft** [comment]
I do believe this behavior has been patched previously. Only requirement is that the biome must be "Hell" and the block "bedrock" must be on the blacklist of blocks to rtp onto. If you can, please copy your config.yml file and send me a copy of it

**Comment by HexedHero** [comment]
> I do believe this behavior has been patched previously. Only requirement is that the biome must be "Hell" and the block "bedrock" must be on the blacklist of blocks to rtp onto. If you can, please copy your config.yml file and send me a copy of it

Config was pretty much default, only thing changed was to use the worldborder, I added bedrock to the blacklist and obv that fixed it.
Bedrock should be on by default I feel :P
