### ISSUE TITLE
1.8 Error

### ISSUE THREAD

**Issue by illudota** [SuperRonanCraft/BetterRTP#102]
**Plugin Version**:
3.4.2-2

**Describe The Bug**:
Error when player join? not sure but yeah it seems like it

**How To Reproduce**:
1. Install fresh BetterRTP on 1.8.8
2. Join the server
3. you'll get this error, make sure it's 1.8.8

**Expected Behavior**:
error in console

**Screenshots/Error Log**:
https://pastebin.com/yynrCFZ7
error
whole log:
https://mcpaste.io/79bbff087a9a31cc

**Additional Context**:

**Comment by illudota** [comment]
https://pastebin.com/DYLVxjX4
also this when /rtp, I was opped btw.

**Comment by SuperRonanCraft** [comment]
I have a patch ready to go to fix this, I will be posting this very soon!

**Comment by illudota** [comment]
> I have a patch ready to go to fix this, I will be posting this very soon!

Is this now fixed in 3.4.3?

**Comment by SuperRonanCraft** [comment]
Hey, sorry for not communicating, 3.4.3 was supposed to fix it, but apparently it was an unrelated issue. Just pushed over a patch version 3.4.4 which should fix this! https://www.spigotmc.org/resources/betterrtp.36081/update?update=460320
