### ISSUE TITLE
Players kicked when rtping

### ISSUE THREAD

**Issue by MithrandirCraft** [SuperRonanCraft/BetterRTP#104]
**Plugin Version**:
3.4.3

**Describe The Bug**:
Some players get kicked after teleporting with /rtp, I suspect this may be related to chunk loading. May actually be a Paper issue? Any advice?

**How To Reproduce**:
Basically using /rtp, but I'm afraid this isn't consistent. I didn't even try it on a new server because it only happens to certain players.

**Expected Behavior**:
No server kick when using /rtp.

**Screenshots/Error Log**:
Client error:
![imagen](https://user-images.githubusercontent.com/6623704/173464750-6cf513f0-f885-4d36-8841-a9e8ba1b0e9c.png)

Couldn't find any errors on console yet, but I'll keep an eye out for them.

**Additional Context**:
Keep in mind this only happens using /rtp, the player testing this got kicked every single time he used the command, but wasn't kicked using other command, so there may be something unique about rtp that is triggering this... Most probably the chunk load amount?

**Comment by good3n** [comment]
They're likely on a 1.19 client. Hopefully within the next couple days we get a BetterRTP update with 1.19 support. 🤞

**Comment by MithrandirCraft** [comment]
If 3.4.4 was suppused to fix this, it didn't. Please reopen.

**Comment by MithrandirCraft** [comment]
This is fixed when updating ViaVersion to 4.3.2-SNAPSHOT

**Comment by IGNGf9** [comment]
I am having this same issue even after updating ViaVersion

**Comment by TheIntolerant** [comment]
> I am having this same issue even after updating ViaVersion

Try using the dev build for ViaVersion, that fixed my issue with another plugin.

[ViaVersion Dev Build](https://ci.viaversion.com/job/ViaVersion-DEV/)
[ViaBackwards Dev Build](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/)
