### ISSUE TITLE
Plugin not respecting DisabledWorlds

### ISSUE THREAD

**Issue by Roman-Emperor-42** [SuperRonanCraft/BetterRTP#105]
**Plugin Version**:
3.4.4

**Describe The Bug**:
The plugin will not repect the DisabledWorlds option in config.yml. I have all worlds disabled but one and it still lets you rtp in all of the worlds.

**How To Reproduce**:
https://pastebin.com/EuQk3HAW
Here is my config and my /rtp info worlds 

**Expected Behavior**:
not allow you to rtp in other worlds

**Screenshots/Error Log**:
https://pastebin.com/EuQk3HAW

**Additional Context**:
Ask if you need any other information please.

**Comment by iiMilan** [comment]
Can you provide a video of you RTP'ing in a disabled world?

**Comment by SuperRonanCraft** [comment]
literally not possible, reopen with proof :D
