### ISSUE TITLE
[BUG]Client Crash When Using Random Teleport

### ISSUE THREAD

**Issue by ZoruaFox** [SuperRonanCraft/BetterRTP#106]
**Plugin Version**:
3.4.4

**Describe The Bug**:
When player use /rtp to teleport randomly, they will be strangely "kicked" out, left a kick message saying, 
`Internal Exception: io.netty.handler.codec.DecoderException: Received unexpected null component.`
Console shows no ERRORs or WARNs.

**How To Reproduce**:

1.Join the server 
2.Use /rtp
3.Situation happend.

**Expected Behavior**:
_None_

**Screenshots/Error Log**:
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/96456728/174571150-936cc5ac-08bc-48bd-8848-1348353b4388.png">

### **↓Maybe IMPORTANT↓**
**Additional Context**:

This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)

My server use ViaVersion to let player join the server by different versions of clients, when player use 1.18.2(same as server) to join the server, the bug WONT HAPPEN. When player use 1.19 to join the server ,the bug ALWAYS HAPPEN.

**Comment by iiMilan** [comment]
Hi,

If you use the latest ViaVersion dev build this won't happen anymore.

Greetings.

**Comment by ZoruaFox** [comment]
> Hi,
> 
> If you use the latest ViaVersion dev build this won't happen anymore.
> 
> Greetings.

I find the latest version of ViaVersion is 4.3.1.
Should I use this one from **Release** or something else(such as the newest artifact in their **Action**)?

**Comment by iiMilan** [comment]
The DEV build can be found in there discord. I will send you a link under this. Keep in mind that it instantly downloads the .jar file.

This fixes the issue with ViaVersion. BetterRTP works on 1.19 based servers but hasn't officially released yet.

https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.3.2-SNAPSHOT.jar

**Comment by ZoruaFox** [comment]
> The DEV build can be found in there discord. I will send you a link under this. Keep in mind that it instantly downloads the .jar file.
> 
> This fixes the issue with ViaVersion. BetterRTP works on 1.19 based servers but hasn't officially released yet.
> 
> https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.3.2-SNAPSHOT.jar

My appreciation to you for your help, the bug has been solved completely.
