### ISSUE TITLE
some players gets disconnected after rtp

### ISSUE THREAD

**Issue by realGretix** [SuperRonanCraft/BetterRTP#110]
**Plugin Version**:

**Describe The Bug**:

**How To Reproduce**:

**Expected Behavior**:

**Screenshots/Error Log**:

**Additional Context**:

**Comment by realGretix** [comment]
Plugin Version: 3.4.4

Describe The Bug: Some players gets disconnected after rtp

How To Reproduce:
- use /rtp command
- get kicked

Expected Behavior: I expect all players to be telleported normally

Screenshots/Error Log: 
![image](https://user-images.githubusercontent.com/62449290/183264076-d1251b52-b6dc-4e32-80aa-0b0504ce7971.png)


Additional Context:

**Comment by realGretix** [comment]
my server runs for both 1.18 and 1.19 and players get kicked only on 1.19 with error "Received unexpected null component"

**Comment by realGretix** [comment]
and my paper version is 379 1.18.2

**Comment by ZoruaFox** [comment]
> and my paper version is 379 1.18.2

Are you using “Viaversion”？

**Comment by ZoruaFox** [comment]
#106 
the same issue

**Comment by SuperRonanCraft** [comment]
Issue #106 should solve the issue, not a problem with RTP but with packets in the latest 1.19 builds using ViaVersion or any other packet translation layer
