### ISSUE TITLE
Particle effects on teleport not functional in 1.19.2

### ISSUE THREAD

**Issue by Weasel-Beans** [SuperRonanCraft/BetterRTP#112]
**Plugin Version**:
3.4.4

**Describe The Bug**:
With either the default configuration or a custom setting, the particle effects in effects.yml is no longer functional in 1.19.2. Nothing appears on teleport as if it was set to disabled.

**How To Reproduce**:
Use Pufferfish 1.19 #36 (or other server software presumably), BetterRTP 3.4.4, and attempt the RTP function.

I've seen other reports of this bug in the Discord.

**Comment by SuperRonanCraft** [comment]
Hey mate, thanks for letting me know! Just a quick update to the ParticleLib API and they all seem to be working again ;) I'll be releasing an update on this soon!

**Comment by SuperRonanCraft** [comment]
This has been fixed in version 3.4.5 ;)
https://www.spigotmc.org/resources/betterrtp.36081/update?update=475857
