### ISSUE TITLE
Support for HuskTowns

### ISSUE THREAD

**Issue by xF3d33** [SuperRonanCraft/BetterRTP#113]
**Plugin Version**:
3.4.4

**Request**:
Add support for HuskTowns claims
https://github.com/WiIIiam278/HuskTowns

**How/Why**:
With his api

**Comment by SuperRonanCraft** [comment]
added support for this in version 3.4.5 ;)
https://www.spigotmc.org/resources/betterrtp.36081/update?update=475857
