### ISSUE TITLE
Make sql querys async

### ISSUE THREAD

**Issue by Zoltus** [SuperRonanCraft/BetterRTP#115]
Messaged to u at spigot month ago but no response so here again

You should always execute sql querys async, which you are not doing.
It can be a huge problem!
For example querys in public List<QueueData> getInRange(QueueRangeData range)
arent async.

**Comment by SuperRonanCraft** [comment]
I can assure you all sql querys are called Async, the reason they are not EXPLICITELY called async is cause the majority of these are called in a method that is already running Async. You can check, in RTPPlayer, the [getApplicable ](https://github.com/SuperRonanCraft/BetterRTP/blob/33a25bccab646b39d267d20402ec2f6b74b9c406/src/main/java/me/SuperRonanCraft/BetterRTP/references/rtpinfo/QueueHandler.java#L56) is called async from the RTPPlayer class ;)

**Comment by Zoltus** [comment]
> getInRange

If you execute CmdInfo#execute it calls infoGetWorld
which calls QueueHandler.getApplicableAsync(_rtpworld).size());
which class DatabaseHandler.getQueue().getInRange(new DatabaseQueue.QueueRangeData(rtpWorld));

And mayby im blind but I cant see where it turns into async there.

**Comment by SuperRonanCraft** [comment]
Oh, well that info command is harmless, only admins have access to it and only used when setting up. I will fix that up though, simple fix luckily.
Thanks for pointing that out

**Comment by Zoltus** [comment]
> Oh, well that info command is harmless, only admins have access to it and only used when setting up. I will fix that up though, simple fix luckily. Thanks for pointing that out

Np:)

**Comment by SuperRonanCraft** [comment]
took me long enough...
