### ISSUE TITLE
Locations not working

### ISSUE THREAD

**Issue by LcyDev** [SuperRonanCraft/BetterRTP#117]
**Plugin Version**:
3.6.1

**Describe The Bug**:
No matter how far the location coords are, the plugin always teleports to the same general area of the map

**How To Reproduce**:
Locations should teleport in a radius of the specified area

**Expected Behavior**:

**Screenshots/Error Log**:
No errors in console

**Additional Context**:
I have a earth map and tried to add different locations for continents but it always teleports me to africa

**Comment by LcyDev** [comment]
https://paste.gg/p/ConaII_/223ba1b9b31b41b680c900895e563f94
I have to use BetterRTP-3.3.0 because both BetterRTP-3.5.0 and BetterRTP-3.6.1 have inacurrate location teleport. 
I didn't test 3.4.0 though

**Comment by SuperRonanCraft** [comment]
Locations call upon the Default world settings in the config.yml, if you have UseWorldBorder set to `true` in the default section, and nothing in the locations, try adding the node `UseWorldBorder ` and set it to false, else the locations will just recenter in the middle of your vanilla worldborder
