### ISSUE TITLE
BetterRTP take long and tp really far away ?

### ISSUE THREAD

**Issue by At0micA55** [SuperRonanCraft/BetterRTP#12]
**Plugin Version**:
<Version #2.8.4>

**Describe The Bug**:
<The plugin take a good 5 seconds to ba able to rtp the player and for exemple, i do /rtp at 0 64 0 i get tp to 16930214 64 29948382 I know i don't have a world border but it's supposed to work without them and maybe not give a so high number ? >

**How To Reproduce**:
<Do /rtp and wait xD>

**Expected Behavior**:
<I Would expect the plugin to teleport player that use /rtp to maybe teleport them 10-20k blocks away from where they... >

**Screenshots/Error Log**:
<Don't have any cause it's not necessary for the issue>

Thank you... If this is not an issue and it's cause simply cause i don't have a world border i would be more then happy to get some help with the world border setup :)

**Comment by SuperRonanCraft** [comment]
Try setting 'UseWorldBorder' to false so it doesn't use the vanilla worldborder

**Comment by At0micA55** [comment]
Worked ! I also changed theses values : 

`Settings:
  RespectWorldGuard: false
  RespectGriefPrevention: false
  RespectSavageFactions: false
  MinRadius: 1000
  MaxAttempts: 2
  Cooldown:
    Enabled: true
    Time: 10
  Delay:
    Time: 0
    CancelOnMove: true
  DisableUpdater: false
Default:
  UseWorldBorder: false
  Biomes: []
  MaxRadius: 30000
  MinRadius: 100
  CenterX: 0
  CenterZ: 0`
