### ISSUE TITLE
1.19.3 Update

### ISSUE THREAD

**Issue by TigerRageMC** [SuperRonanCraft/BetterRTP#122]
**Plugin Version**:
3.6.1

**Describe The Bug**:
On the new mc version 1.19.3 the plugin works but there are some errors reporting in console.

**How To Reproduce**:
Update your server to 1.19.3 

**Screenshots/Error Log**:
**[ERROR] [BetterRTP] The particle 'EXPLOSION_NORMAL' created a fatal error when loading particles! Your MC version isn't supported!**

**Comment by LcyDev** [comment]
For now disable particles in `effects.yml`

**Comment by LcyDev** [comment]
This is due to particles changing names https://minecraft.fandom.com/wiki/Particles

Changing them on the file won't work as the code must be updated

**Comment by SuperRonanCraft** [comment]
Fixed in 3.6.2 :)
