### ISSUE TITLE
[Lands] Nag author(s) of plugin BetterRTP. It uses the deprecated LandsIntegration of Lands

### ISSUE THREAD

**Issue by apatuka** [SuperRonanCraft/BetterRTP#123]
**Plugin Version**:
3.6.1

**Request**:
The latest update of Lands made changes on the API, since BetterRTP offers support for Lands.
I'm attaching the error: [Lands] Nag author(s) of plugin BetterRTP. It uses the deprecated LandsIntegration of Lands: https://github.com/Angeschossen/LandsAPI/wiki/API-Update

**How/Why**:
It's just an update of the API to be considered.

**Additional Context**:
Nothing else. Thank you.

**Comment by SuperRonanCraft** [comment]
Hey, thanks for the update, just fixed this recently! Sorry for the late reply, haven't been able to compile BetterRTP for a better part of a month now with recent api updates

**Comment by SuperRonanCraft** [comment]
Patch has been published :D
