### ISSUE TITLE
/rtp biome not working

### ISSUE THREAD

**Issue by SkuadMC** [SuperRonanCraft/BetterRTP#18]
**Plugin Version**: 2.9.3

**Describe The Bug**: /rtp biome <biomename> doesn't do anything different from /rtp. 

**How To Reproduce**:
1. Add this plugin to a server (I'm using Paper-89 for 1.15.2)
2. Try and use /rtp biome <biome>

**Expected Behavior**:
I expected it to land me in the biome I specified, but it's seemingly the same as normal /rtp.

**Screenshots/Error Log**:
No errors.

**Comment by SuperRonanCraft** [comment]
"/rtp biome" takes an argument, there is where you specify the biomes you want to be Rtp'd in

**Comment by SkuadMC** [comment]
Sorry I forgot to mention, I'm testing it using a few different biomes as the argument. Like I tried it with Plains and I landed in a desert a few times as well as a forest. Trying it with any biome just doesn't seem to actually teleport you to that biome.

**Comment by SuperRonanCraft** [comment]
Okay. I will give it a try. If possible could you get me a copy of your betterrtp config in a https://hastebin.com url?

**Comment by SkuadMC** [comment]
https://hastebin.com/halorosaya.bash
Sorry for the late response. 

Also, after a restart today I have people randomly teleporting into blocks or high in the air when they use /rtp. This was also mentioned on the discussion thread on Spigot.

**Comment by SuperRonanCraft** [comment]
Awesome, I will give it a try soon, I will update you

**Comment by SkuadMC** [comment]
Any updates?
