### ISSUE TITLE
BetterRTP prevent my server from starting

### ISSUE THREAD

**Issue by Cnzw** [SuperRonanCraft/BetterRTP#19]
**Plugin Version**:
Lastest version 2.9.3

**Describe The Bug**:
When the server starts
It blocked my server from starting and other plug-ins from loading
Server log stopped at [BetterRTP] Enabling BetterRTP v2.9.3
Players can't join games

**How To Reproduce**:

**Expected Behavior**:
Let it work

**Screenshots/Error Log**:
Just stop at [13:05:25 INFO]: [BetterRTP] Enabling BetterRTP v2.9.3
[13:05:27 WARN]: [ChestCommands] Could not contact BukkitDev to check for updates.
[13:15:51 INFO]: UUID of player xxx is 9568d3cb-0ec2-3579-bdb8-369833541126
Keep this up until the server is forced to end，no other error log

**Additional Context**:
My English is not good,but I think my meaning is clear

**Comment by Cnzw** [comment]
server core:paper 1.12.2
config.yml is default

**Comment by SuperRonanCraft** [comment]
BetterRtp seems to be starting normally. Have you tried disabling other plugins, maybe you are running out of server memory, causing a crash after so many plugins
