### ISSUE TITLE
Teleport in blocks

### ISSUE THREAD

**Issue by Ziomkeee** [SuperRonanCraft/BetterRTP#21]
**Plugin Version**: 2.9.3

**Describe The Bug**: Teleports to a random place, but throws the player into blocks.

**How To Reproduce**:
1. I uploaded it to paper 1.15.2 (paper-93)
2. I've done the configuration
3. I used rtp

**Expected Behavior**: It should teleport to a safe place, not a stone or other block.

**Screenshots/Error Log**: ...

**Comment by TheStaticVoid** [comment]
having same issue

**Comment by mrfloris** [comment]
Same here. It's because Spigot 1.15.2 changed something in a recent --rev 1.15.2 build.

**Comment by morfie78** [comment]
I have the same issue.  Is this a thing that will be fixed via Spigot or fixed inside this plugin?

**Comment by Ziomkeee** [comment]
> 
> 
> I have the same issue. Is this a thing that will be fixed via Spigot or fixed inside this plugin?

I used a different plugin :)

**Comment by SuperRonanCraft** [comment]
Bug has been fixed in 2.10.0 ;)

**Comment by morfie78** [comment]
Thank you!
