### ISSUE TITLE
/rtp biome not working

### ISSUE THREAD

**Issue by SkuadMC** [SuperRonanCraft/BetterRTP#23]
Plugin Version: 2.9.3

Describe The Bug: /rtp biome doesn't do anything different from /rtp.

How To Reproduce:

Add this plugin to a server (I'm using Paper-89 for 1.15.2)
Try and use /rtp biome PLAINS (or any biome is fine)
Expected Behavior:
I expected it to land me in the biome I specified, but it's seemingly the same as normal /rtp.

Screenshots/Error Log:
No errors.

**Comment by SuperRonanCraft** [comment]
@SkuadMC I do believe the biome command works on Spigot and Bukkit based servers, I have no way to test on a Paper based server, if possible, could you test on a Spigot based server and see if it works there for you?
