### ISSUE TITLE
Towny Support

### ISSUE THREAD

**Issue by JohnS19** [SuperRonanCraft/BetterRTP#27]
**Plugin Version**:

2.10.1
**Request**:

Add towny claim support similar to worldguard support. 
**How/Why**:

This feature would allow players to only teleport into areas where they have access to, rather than randomly teleporting into another town's house and being stuck.
**Additional Context**:

**Comment by SuperRonanCraft** [comment]
I will see if I can implement this, would this be the plugin page you mean for [Towny](https://www.spigotmc.org/resources/towny-advanced.72694/) (I've never used it)? Also, if possible, could you direct me to a integrations page to be able to find it a little bit quicker

**Comment by JohnS19** [comment]
Yes, that is the plugin page.

https://github.com/TownyAdvanced/Towny/wiki/TownyAPI#getting-started-with-towny-and-your-ide

**Comment by SuperRonanCraft** [comment]
Alright, I am currently getting back to working on the project, I will try to add Towny support when possible, I will let you know if/when its been added on my local machine.

**Comment by JohnS19** [comment]
Sure, thanks.

**Comment by DarkEyeDragon** [comment]
Just came across this plugin and looks good so far! I've done towny support this in my rtp plugin: https://github.com/DarkEyeDragon/RandomTeleport/blob/dev/src/main/java/me/darkeyedragon/randomtp/validator/TownyValidator.java 

Essentially just check if the location is in wilderness or not, or whatever constraints you want. The api is alright to use.

**Comment by SuperRonanCraft** [comment]
this will be added in 2.12.3 coming very soon ;)
