### ISSUE TITLE
RTP Signs

### ISSUE THREAD

**Issue by Jacohun1** [SuperRonanCraft/BetterRTP#28]
**Plugin Version**:
2.10.1

**Request**:
Ability to create and use RTP Signs

**How/Why**:
It makes it really nice for players to be able to click when in spawn and other areas

**Additional Context**:
https://gyazo.com/c7943cf4557b6567b9b3b7e87dcf9347

**Comment by DrakePork** [comment]
This is already in the plugin though? If you go into the plugin folder and then go into signs.yml you can then enable signs. the Title is supposed to go on the top part of the sign.
