### ISSUE TITLE
BetterRTP teleporting players on air

### ISSUE THREAD

**Issue by CosmicQueso** [SuperRonanCraft/BetterRTP#29]
**Plugin Version**: 
2.10.1

**Issue Type**: 
Configuration Bug

**Context**:
In the Config.yml file, there is a section for Blacklisted Blocks, this is the current/active version of the file (for blacklisted blocks) on a server I work for:
`BlacklistedBlocks:`
`- stationary_water`
`- stationary_lava`
`- water`
`- lava`
`- cactus`
`- leaves`
`- leaves_2`
`- air`

However, people still die in End after the using /rtp due to teleporting in air and then falling into the void.

**Comment by SuperRonanCraft** [comment]
Depending on the minecraft version. You must also add a block for the void. You must add that to support the end ;)
