### ISSUE TITLE
Cooldown being buggy when small

### ISSUE THREAD

**Issue by DrakePork** [SuperRonanCraft/BetterRTP#31]
**Plugin Version**: 2.10.1

**Describe The Bug**:
If you have your rtp cooldown on for example 7-10 seconds it will bug where you can type /brtp again if you type it quick enough after being rtped. Doesnt happen on any big cooldowns like 600 seconds for example.

**How To Reproduce**:
1 - Set cooldown to 7 seconds
2 - Do /brtp
3 - Do /brtp again right after you have teleported to the new location.

**Expected Behavior**:
For the cooldown to apply instantly.

**Comment by SuperRonanCraft** [comment]
I do see that issue, slight oversight. If you rtp after a cool-down, the cool-down is reset, so the plugin things you never rtp'd before. Doesn't matter the time actually. I will get this ironed out as soon as I can

**Comment by SuperRonanCraft** [comment]
This bug has been fixed, but I am still working on getting some other additions and bugs before I release

**Comment by SuperRonanCraft** [comment]
Just posted an update earlier, forgot to mention this is the update, but it should be patched ;)
