### ISSUE TITLE
Make economy part of plugin reload with /brtp reload

### ISSUE THREAD

**Issue by DrakePork** [SuperRonanCraft/BetterRTP#32]
**Plugin Version**: 2.10.1

**Request**:
When typing /brtp reload, make the economy part of the plugin reload properly with it, as right now it does not reload properly with /brtp reload. (For example when disabling or enabling economy)

**How/Why**:
Should be added so players dont have to restart their server completely to enable economy.

**Comment by SuperRonanCraft** [comment]
Good catch, didn't realize it, but the economy is actually never loaded on start up, only loaded when an rtp command was requested. I will fix this for the next patch coming very soon!
