### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Christofmeg** [SuperRonanCraft/BetterRTP#36]
**Plugin Version**:
2.11.0

**Describe The Bug**:

**How To Reproduce**:
Play on spigot 1.14.4
Have an alias /rtp for /betterrtp
Fullrender dynmap tiles at a rate of 82.00 msec/tile
Do /rtp
Then /betterrtp after a few secound, but before the first rtp had started.

**Expected Behavior**:
Did /betterrtp, expected to get randomly teleported somewhere.

**Screenshots/Error Log**:
https://hastebin.com/fazozodatu.md

**Additional Context**:
NTR i guess.

**Comment by SuperRonanCraft** [comment]
This is most likely because you have a rather large rtp range. Make sure your configuration is setup and check the parameters of the world with '/rtp info'

**Comment by Christofmeg** [comment]
I will try that! thanks
