### ISSUE TITLE
Usability with command blocks

### ISSUE THREAD

**Issue by Clyred** [SuperRonanCraft/BetterRTP#4]
**Plugin Version**:
2.7.6

**Request**:
I'd like to ask you about ability of using /rtp command in command blocks. ( /rtp player @p ) will be nice for example. Thanks.

**How/Why**:
Bcause for now it's impossible to use it in command blocks.

**Additional Context**:
![screenshot_1](https://user-images.githubusercontent.com/37591892/50857331-5565b480-139e-11e9-8ca7-d43bde5152dd.png)

**Comment by HexedHero** [comment]
I'd like this to be added too
maybe this would work
https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/
not sure tho.

**Comment by At0micA55** [comment]
HexedHero what if you use the simple rtp @p world_nether ?
Or
rtp world @p world_nether ?

**Comment by SuperRonanCraft** [comment]
Yeah, forgot to reply to this ticket a while ago. Command blocks have a special way they use @ messages, so you need to use a command block plugin that allows the @ in a command block for plugin commands
