### ISSUE TITLE
Increase Chunks Load Radius Before Teleporting

### ISSUE THREAD

**Issue by kn-km** [SuperRonanCraft/BetterRTP#41]
**Plugin Version**:

2.12.2
**Describe The Bug**:

I suggest to increase chunk load radius to at least 1 higher than the view-distance.
Because the chunk player in is not included in vanilla Minecraft Chunk loading. But it is included in the code you are currently using. You should make a small refactoring to solve this problem.
There are two ways to solve it:
1.  Make it configurable in config.yml.
2.  Increase chunk load radius by at least 1.

Thank you!

**How To Reproduce**:
None.

**Comment by SuperRonanCraft** [comment]
I will be making this configurable, thank you for your suggestion!
