### ISSUE TITLE
[Bug/Maybe intended feature] Shows players displayname on command /rtp player (player) instead of playername.

### ISSUE THREAD

**Issue by AZFire1** [SuperRonanCraft/BetterRTP#42]
**Plugin Version**:
25.09 22:03:13 [Server] INFO SOUP RTP ? Version #2.13.1

**Describe The Bug**:
I've noticed that Essentials has a feature where it modifies the displayname of users for it's own chat plugin. Well, it looks like it changes the displayname globally throughout the server. When I do /rtp player (player), instead of giving me the playername it gives me the player displayname to put.. When I try any of the displaynames (with the prefix/suffix because of essentials) it doesn't work.

**How To Reproduce**:
Have a plugin that modifies the displayname of a user such as essentialschat.
Attempt doing /rtp player 
Notice it recommends player names with the ranks with the prefix/suffix that essentials adds.

**Expected Behavior**:
For BetterRTP to only recommend the players unmodified name if possible.

**Screenshots/Error Log**:
![Screenshot for RTP](https://user-images.githubusercontent.com/67762583/94311428-4693ac80-ff49-11ea-9cb3-2cc92d7647b8.png)

**Additional Context**:
None.

**Comment by SuperRonanCraft** [comment]
oh, lol that is actually hilarious, I think the spigot api allows me to get around that. I will get an update for this soon

**Comment by SuperRonanCraft** [comment]
Alright, I do believe I have a fix for this on my builds. I will push an update when possible
