### ISSUE TITLE
Error spammed in console

### ISSUE THREAD

**Issue by Plum1111** [SuperRonanCraft/BetterRTP#45]
**Plugin Version**:
2.14.0

**Describe The Bug**:
Console spams an error message, nothing bad happens to my knowledge

**How To Reproduce**:

Just install the plugin - it happened on a fresh install on a newly generated config

**Expected Behavior**:
No error spammed in console

**Screenshots/Error Log**:
https://pastebin.com/dMvmKtx5

**Additional Context**:
I tried really hard to see what was wrong in the config file but I just couldn't find anything so I thought it was a problem with the plugin itself. I might be wrong though.

**Comment by SuperRonanCraft** [comment]
I've done various fresh installs on a Windows and Linux based server and can't find the issue. I would assume you've changed a language file and it was configured incorrectly. I would use a yaml checker like https://yamlchecker.com/ and make sure the language file you are using is setup correctly.

**Comment by Plum1111** [comment]
Every single one of the files was valid, I hadn't changed them. I have now deleted them for a third time and it works now. Please don't ask why this is because I have deleted them before but that fixed the problem.
