### ISSUE TITLE
Use setBedSpawnLocation on RTP on first join

### ISSUE THREAD

**Issue by Flying--Dutchman** [SuperRonanCraft/BetterRTP#47]
**Plugin Version**:
BetterRTP v2.14.3

**Request**:
Use `setBedSpawnLocation` after teleport on first join, so that players stay on their spawn point, even after death.

**How/Why**:
Currently, if a player dies before setting a spawn point, the player gets back at the world spawn.

A way to implement this would be:
```
event.getPlayer().setBedSpawnLocation(event.getPlayer().getLocation(), true);
```

**Comment by SuperRonanCraft** [comment]
Not an issue, I will try to implement it as best as I can!
