### ISSUE TITLE
Add the ability to return players back after they RTP'd after an amount of time

### ISSUE THREAD

**Issue by IsXGeo** [SuperRonanCraft/BetterRTP#48]
**Plugin Version**:
Version #2.14.4

**Request**:
The ability to make it so that players can be returned to the place where they RTP'd from after an amount of time.

**How/Why**:
Why: I am running a skyblock server and I want my players to be able to pay an amount of money to be teleported somewhere random in another world in order to collect resources, kill mobs, etc before being teleported back to their island.

**Comment by SuperRonanCraft** [comment]
I think this is a great addition, but it's so specific that I might start do these small additions with addons, something I've been wanting to do for a while.
I will let you know when I add some, it will be a plugin of its own, completely free of course, but I think it will allow for some nice updates in the future.
I will close this for now, but I will be working on this in the background.

**Comment by SuperRonanCraft** [comment]
@IsXGeo So I have some good news, I will be making an addons support for the plugin, so these small features you will be able to have with an additional plugin. I'm not sure exactly when this will be released, but I will let you know when it's released. So far I've added a "FlashBack" feature that allows you to control when to teleport a player back after a random teleport.

**Comment by IsXGeo** [comment]
Awesome that sounds great so far, looking forward to it

[Joshua Doody - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=rn0go)	[rn0go]

On November 11, 2020 at 22:40 GMT, RonanCraft <notifications@github.com> wrote:

[@IsXGeo](https://github.com/IsXGeo) So I have some good news, I will be making an addons support for the plugin, so these small features you will be able to have with an additional plugin. I'm not sure exactly when this will be released, but I will let you know when it's released. So far I've added a "FlashBack" feature that allows you to control when to teleport a player back after a random teleport.

**Comment by SuperRonanCraft** [comment]
Here's a quick preview of what's to come on the addons plugin ;)

![image](https://user-images.githubusercontent.com/7385626/99896193-39025680-2c5c-11eb-976e-d4362f2a4d44.png)

**Comment by IsXGeo** [comment]
That looks great, and will probably work much better than my janky skript bodge. Can I ask however, is it able to remember a players information, say if the server restarts, crashes, player disconnects, etc so that people aren't left stranded?

**Comment by SuperRonanCraft** [comment]
Yes, that was the first thing I wanted to implement was cached memory of a players last rtp'd location over restarts. So far it works great, and even if a player leaves after they should have been teleported back, the moment they join they will telepoeted back no matter what

**Comment by IsXGeo** [comment]
Awesome, looking forward to its release
