### ISSUE TITLE
make lang file available to fork and translate

### ISSUE THREAD

**Issue by DirolGaming** [SuperRonanCraft/BetterRTP#5]
**Plugin Version**:

-
**Request**:

Make the lang files available on the GitHub page so users can fork the project and translate the files and create a pull request.
**How/Why**:

Because it would make adding support for new languages easier.
**Additional Context**:

**Comment by SuperRonanCraft** [comment]
Sorry for the long delay O-O
Haven't looked on Github for a while, I did just add the lang file on here for ya :)
