### ISSUE TITLE
Link to lang files is broken

### ISSUE THREAD

**Issue by jordi2010** [SuperRonanCraft/BetterRTP#50]
**Screenshots/Error Log**:

![image](https://user-images.githubusercontent.com/37302148/100866840-88852580-3499-11eb-9d0c-604bd2be98b9.png)

**Additional Context**:

Link isn't working anymore on the github repo.

**Comment by SuperRonanCraft** [comment]
Ha, thank you for letting me know! I fixed it up 😄
