### ISSUE TITLE
Placeholder API

### ISSUE THREAD

**Issue by Blzd87** [SuperRonanCraft/BetterRTP#58]
**Plugin Version**:
304-1

**Describe The Bug**:
the placeholder api doesnt seem to work or pull data to display im trying to display the Biome to the player once they've rtp'd but all it shows is %player_biome%...

**How To Reproduce**:
Teleport:
    Title: '&6%player_biome%'

**Expected Behavior**:
thought it would just display the current biome to the player.

**Screenshots/Error Log**:
https://img.justblzd.com/2021-02-02_20.18.18.png

**Comment by SuperRonanCraft** [comment]
I do believe titles don't support Placeholder API. I will see if I can add this for the next patch ;)

**Comment by SuperRonanCraft** [comment]
Now that I actually have placeholder api in the plugin adding some placeholders, next patch I will make sure all messages support placeholders. To be added soon!

**Comment by SuperRonanCraft** [comment]
As of 3.5.1, placeholders have been added! 😄
