### ISSUE TITLE
[Request] Griefdefender respect setting

### ISSUE THREAD

**Issue by hkkongou** [SuperRonanCraft/BetterRTP#60]
**Plugin Version**:

version 3.0.5

**Request**:

Setting add respect grief defender GD, i saw betterrtp respect support many claim plugin but not this.

**How/Why**:

As grief defender is becoming famous , more people will use it. However, betterrtp does not respect it and so, rtp will often tp to GD claims.

**Additional Context**:

**Comment by SuperRonanCraft** [comment]
Sorry for not responding! I swore I did, but this has been added and will be released in 3.1.0!
