### ISSUE TITLE
Placeholder show times cooldown

### ISSUE THREAD

**Issue by Baschounette** [SuperRonanCraft/BetterRTP#66]
**Plugin Version**: Version #3.1.1

**Request**:
I would like a Placeholder for my menu which show the times cooldown staying before player use /rtp again.
This placeholder will use in lore for a button in my menu because I use you're plugin with menu.

**How/Why**:
I think it could be great :)

An example : [https://zupimages.net/viewer.php?id=21/15/jtm6.png](url)

**Comment by SuperRonanCraft** [comment]
I would like this feature, I will implement it for the next patch ;)

**Comment by Baschounette** [comment]
Hey, so this features could be implemented soon ?

**Comment by SuperRonanCraft** [comment]
Placeholders has now officially been added in version 3.4.5
A file with supported placeholders will generate in the plugin folder!
https://www.spigotmc.org/resources/betterrtp.36081/update?update=475857
