### ISSUE TITLE
Leaves config file reference vs wiki blacklistedblocks different

### ISSUE THREAD

**Issue by crispylegumes** [SuperRonanCraft/BetterRTP#67]
**Plugin Version**: #3.1.0-3
**Describe The Bug**:
Wiki page: https://github.com/SuperRonanCraft/BetterRTP/wiki/Config#blacklistedblocks
- leaves
- leaves_2

Default `config.yml`
- oak_leaves
- jungle_leaves

**How To Reproduce**:
Run a new install and inspect config.yml and compare to wiki page

**Expected Behavior**:
What is the correct format?

**Screenshots/Error Log**:

**Additional Context**:
+ Shouldn't you add support for all types of leaves by default, or is the wiki page correct and the default config file incorrectly listing oak_leaves and jungle_leaves?

**Comment by SuperRonanCraft** [comment]
depends on what Minecraft version you are running. "leaves" are 1.12 and below, just like the Spigot API states https://helpch.at/docs/1.12.2/org/bukkit/Material.html#LEAVES. For newer 1.13+ versions, "oak_leaves" is correct. Reason I haven't bother adding all types of leaves is cause I'd rather have more safe spots by default than having a safe spot thrown away for being above a tree.
