### ISSUE TITLE
Missing API specification with 1.14.

### ISSUE THREAD

**Issue by mibby** [SuperRonanCraft/BetterRTP#7]
Running on 1.14, there seems to be a missing API specification in the plugin.yml.

```
[13:22:53] [Server thread/WARN]: Plugin BetterRTP v2.8.2 does not specify an api-version.
```

**Comment by HexedHero** [comment]
Means nothing. The plugin's native version isn't 1.13+

**Comment by SuperRonanCraft** [comment]
@HexedHero no reason to set a version as the plugin does not mess with items. If this does become a cause of an issue I will be sure to specify one. But for now, no need :)
