### ISSUE TITLE
2.8.2 rtp player <player> not request permission

### ISSUE THREAD

**Issue by comonier** [SuperRonanCraft/BetterRTP#8]
Any player can use RPT Player <Player> <World> command without permission.
there is not a verification from command 
/rtp player player
anyone can use that without permissions.
i did the test on 5 diferent servers, its a version bug.

**Comment by codeblue1337** [comment]
I can confirm this, had to remove the plugin from my server.

**Comment by SuperRonanCraft** [comment]
Extremely sorry for the huge delay, been caught up with work and such. I did just push a patch confirming the fix of this issue ;)
Check it out here: https://www.spigotmc.org/resources/betterrtp.36081/update?update=290160
