### ISSUE TITLE
BetterRTP is doing I/O operations on main thread

### ISSUE THREAD

**Issue by Xemorr** [SuperRonanCraft/BetterRTP#81]
![image](https://user-images.githubusercontent.com/31805746/130332380-f3735648-cf62-4aec-9df2-61bc72a6200c.png)

BetterRTP is saving to files on the main thread, this has consequential effects on server performance. Here it is shown to be using 16% of main thread.

**Comment by Xemorr** [comment]
I decided to have a go at fixing it myself, or at least creating some sort of patch for my own use and I realised that you've also effectively created a memory leak as you're loading the entire file at boot rather than as players join, this means the more and more offline players a server accumulates, the more memory is used.

**Comment by SuperRonanCraft** [comment]
Ha, thank you, I was working on doing a complete rework, this will save me a good amount of time. The memory leak I was aware of, but I do see how it could be an issue on large servers, I will be replacing this with a SQL database VERY soon, just haven't had any time to sit down and program lately.

**Comment by SuperRonanCraft** [comment]
Alright, this has finally been fixed in a build I have been working on, I have moved all Cooldowns to save and load asynchronously. I will be releasing this build very soon after plenty of debugging ;)

**Comment by SuperRonanCraft** [comment]
Was able to completely debug and seems like everything is good to go, please let me know if you find any issues with the new cooldowns saving method ;)

**Comment by Xemorr** [comment]
Awesome, thank you Ronan!
