### ISSUE TITLE
No WorldType declared warning despite type being specified.

### ISSUE THREAD

**Issue by mibby** [SuperRonanCraft/BetterRTP#83]
**Plugin Version**:
``RandomTP » Version #3.1.0-5`` - compiled as of commit https://github.com/SuperRonanCraft/BetterRTP/commit/1c61ac9d6048e18afa2f04645bd79cae12397879

**Describe The Bug**:
I have a button that runs the command ``rtp player <player> rw`` from console. On the first rtp to the world, BetterRTP complains that the WorldType is not declared, despite being declared and existing in the config.

**How To Reproduce**:
1. Add a button that runs the command ``rtp player <player> rw`` from console.
2. Hit the button in the world ``spawn``.
3. Get randomly teleported to the ``rw`` world.
4. BetterRTP complains.

**Expected Behavior**:
No warning when RTPing into the world for the first time.

**Screenshots/Error Log**:
```
[13:16:05] [Server thread/WARN]: [BetterRTP] Seems like the world `rw` does not have a `WorldType` declared. Please add/fix this in the config.yml file! This world will be treated as an overworld!
```

**Additional Context**:

In the config.yml
```
WorldType:
- world: NORMAL
- world_nether: NETHER
- world_the_end: NORMAL
- rw: NORMAL
```

**Comment by SuperRonanCraft** [comment]
mhh, this might be caused because this world might be loading in after the server starts up. Any plugins you are using to spawn in this custom world so I can debug the issue.

**Comment by mibby** [comment]
Just Multiverse. RW is just a simple secondary world for resource gathering, no plugins generate that world.

**Comment by mibby** [comment]
Nope, unfortunately it seems Multiverse loads after BetterRTP.

```
	Line 74: [08:00:21] [Server thread/INFO]: [BetterRTP] Loading BetterRTP v3.1.0-5
	Line 77: [08:00:21] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v4.3.1-b861
	Line 369: [08:00:36] [Server thread/INFO]: [BetterRTP] Enabling BetterRTP v3.1.0-5
	Line 373: [08:00:36] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
	Line 374: [08:00:36] [Server thread/INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
	Line 409: [08:00:39] [Server thread/INFO]: [Multiverse-Core] World 'witp' was unloaded from Multiverse.
	Line 410: [08:00:40] [Server thread/INFO]: [Multiverse-Core] World 'witp' was unloaded from Bukkit.
	Line 411: [08:00:40] [Server thread/INFO]: [Multiverse-Core] World 'witp' was DELETED.
	Line 414: [08:00:40] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'witp' - Env: NORMAL - Type: FLAT & generator: VoidGen
	Line 675: [08:00:51] [Craft Scheduler Thread - 7 - ItemJoin/INFO]: [ItemJoin] Hooked into { Multiverse-Core, PerWorldInventory, WorldGuard, HeadDatabase, PlaceholderAPI, ProtocolLib, Citizens, Vault }
	Line 702: [08:00:52] [Server thread/INFO]: [Magic] Multiverse-Core found, will respect PVP settings
	Line 815: [08:54:13] [Server thread/WARN]: [BetterRTP] Seems like the world `rw` does not have a `WorldType` declared. Please add/fix this in the config.yml file! This world will be treated as an overworld!
```

Making ``Multiverse-Core`` a softdepend in the plugin.yml would probably fix the issue I presume.

**Comment by SuperRonanCraft** [comment]
Oh, oof, I will work on this then, might be an easy fix, just find it weird why Multiverse would load after just for you, when it works for me and many others O_O

**Comment by SuperRonanCraft** [comment]
> Making `Multiverse-Core` a softdepend in the plugin.yml would probably fix the issue I presume.

That would be the easy solution, wish I saw this before I just posted 3.2.0

**Comment by mibby** [comment]
> just find it weird why Multiverse would load after just for you, when it works for me and many others O_O
Most likely because I have quite a heavy plugin environment that adjusts the initialization order of plugins due to different soft & hard dependencies.

I manually added ``Multiverse-Core`` to the plugin.yml softdepends in version 3.1.0-5 and can confirm it seems to fix the issue.

**Comment by SuperRonanCraft** [comment]
Okay, ima put in `loadbefore`, just so I dont get confused in a couple months as say "What did I add for multiverse", should still work the same ;) I will be releasing this in a couple minutes

**Comment by SuperRonanCraft** [comment]
> Why `loadbefore`? Doesn't that make it so BetterRTP will load first? We would want `Multiverse-Core` to load first, then BetterRTP. Otherwise you'll run into the same issue as this ticket since BetterRTP is already loading before Multiverse for me. The only way to ensure that BRTP loads after is to make it a softdepend.

It works the opposite way, I know it doesnt sound like it, but I looked it up, give 3.2.1-1 a try and see if it works, if not let me know once more ;)

**Comment by mibby** [comment]
>  I know it doesnt sound like it, but I looked it up

Where? Spigot wiki clearly states;
https://www.spigotmc.org/wiki/plugin-yml/

_loadbefore_
* A list of plugins that should be loaded after your plugin.
* Your plugin will load before any plugins listed here.

Same with the ancient Bukkit wiki.
https://bukkit.fandom.com/wiki/Plugin_YAML

**Comment by SuperRonanCraft** [comment]
Bahh, good point, my brain is on auto-pilot and wasn't thinking... I will do this asap

**Comment by SuperRonanCraft** [comment]
Uploaded 3.2.1-2 ;)
I'm a good programmer, I swear
