### ISSUE TITLE
Add pliz

### ISSUE THREAD

**Issue by grabeq123** [SuperRonanCraft/BetterRTP#88]
I have the BetterRTP Addon so I'm just waiting for you to add options relying on group RTP to it

**Comment by grabeq123** [comment]
Would you add a command so that some group of people in some kind of beams could randomly stamp together on the same cords?

**Comment by SuperRonanCraft** [comment]
Coming real soon to a plugin near you ;)

**Comment by SuperRonanCraft** [comment]
A new Parties system has been released in the BetterRTP Addons, remember to update the core plugin as well!
