### ISSUE TITLE
Support for RGB/Hexidecimal color formatters

### ISSUE THREAD

**Issue by ArcticRaven** [SuperRonanCraft/BetterRTP#89]
**Request**:
Some RGB formatter (though preferably just #rrggbb as opposed to the terrible {&x&r&r&g&g&b&b}) 

**How/Why**:
It would help with server customization as well as potential usability for high/low contrast color themes.

**Comment by SuperRonanCraft** [comment]
As of 3.3.0 this has been added ;) https://www.spigotmc.org/resources/betterrtp-random-wild-teleport.36081/update?update=449441
