### ISSUE TITLE
Permissions per Location

### ISSUE THREAD

**Issue by mitchngwen** [SuperRonanCraft/BetterRTP#90]
Permissions per location

betterrtp.location.examplelocation

With this we can now make a custom menu that allows for the purchase or unlock of rtp locations.

**Comment by SuperRonanCraft** [comment]
This is something I would like to add actually, I will try to make it happen in a timely manner ;)

**Comment by mitchngwen** [comment]
Awesome! Can't wait. Thank you for your hard work on the plugin!

**Comment by SuperRonanCraft** [comment]
Sorry for not updating this, but this feature has been added since 3.3.0! Check it out here https://www.spigotmc.org/resources/betterrtp-random-wild-teleport.36081/update?update=449441
