### ISSUE TITLE
Plugin compilation failure

### ISSUE THREAD

**Issue by TwinkleToes777** [SuperRonanCraft/BetterRTP#91]
**Plugin Version**: 6700e0bb3f55e7881cc46ea9fdd4333220be00b3

**Issue Type**: Compilation

**Context**: Plugin compilation with maven fails.

[ERROR] Failed to execute goal on project BetterRTP: Could not resolve dependencies for project me.SuperRonanCraft:BetterRTP:jar:3.3.0: The following artifacts could not be resolved: org.bstats:bstats-bukkit:jar:1.7, com.bekvon.bukkit:Residence:jar:4.9.1.9, com.hakan:claimapi:jar:2.1.8: org.bstats:bstats-bukkit:jar:1.7 was not found in https://jitpack.io during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]

**Comment by SuperRonanCraft** [comment]
Add-ons plugin needs the base betterrtp as a dependency, you'd need to look up how u can import a jar as a dependency in maven

**Comment by TwinkleToes777** [comment]
You may have not understood me, I am looking to compile BetterRTP so I can avoid downloading it from SpigotMC (Does not work well for me), I am not making addon.

**Comment by SuperRonanCraft** [comment]
Ah, I just assumed cause I saw version 3.3.0.
My bad, ya will need to import these two dependencies via a jar, the folder named LocalJars has the currently supported jar files, these need to be imported manually via mavens install command

**Comment by SuperRonanCraft** [comment]
If you don't want hclaims or residence support, you could remove those dependencies and remove the erorrs in the one class they are referenced on too btw

**Comment by TwinkleToes777** [comment]
I am getting stuck at bstats dependency, it is not mentioned in pom.xml, so I assume one of the dependencies uses it, but it fails to download it

**Comment by SuperRonanCraft** [comment]
It's used in the Web class, just as a stats thing. You can also delete that class, thwre might have been newer version and I haven't updated possibly
