### ISSUE TITLE
Rtp to region

### ISSUE THREAD

**Issue by skigrex** [SuperRonanCraft/BetterRTP#98]
**Plugin Version**:
<-- 3.2.1 -4-->

**Request**:
<-- Something similar to the customworld, but with region -->

**How/Why**:
<-- ¿How? Using the same way as customworld work, ¿Why? in order to optimize the server, is it much better to have just a big wold with a few region, that 5 diferent worlds-->

**Additional Context**:
<-- In my personal case, because i want to add mazes to my server, and i want to create random spawn -->

**Comment by SuperRonanCraft** [comment]
Hey mate, so this sounds like you want to be using the Locations feature, its the same thing as a region you are explaining here, take a look at how to set it up here on the wiki https://github.com/SuperRonanCraft/BetterRTP/wiki/Locations this is in the locations.yml file btw
